server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**

        - id: school-service
          uri: lb://SCHOOL-SERVICE
          predicates:
            - Path=/school/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
