server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: student-service1
          uri: lb://STUDENT-SERVICE1
          predicates:
            - Path=/student/**

        - id: school-service1-1
          uri: lb://SCHOOL-SERVICE1-1
          predicates:
            - Path=/school/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
